### ISSUE TITLE
SokobanMap.loadSimpleState and method classes

### ISSUE THREAD

**Issue by tpict** [marcusjrc/lbuilder#29]
old comment on the loadSimpleState method:

```java
    /*
     * Is this right to do? For a given state I want to set the map to that
     * position so I can use accessibleSpaces() to work out what boxes you can
     * push from a given SaveState.
     */
```

wouldn't it be better to just give SaveStates an xSize/ySize field and move those methods to the SaveState class?

**Comment by Gantonator** [comment]
The solver loads a state, then pushes, and undoes, and looks at the states that come out of the map.  You could get it to look at only the states if you want but It's easy to understand as it is.

I feel like SaveState IS the map now rather than a representation of the state of the gameplay like it was.  So you can sort it if you want but the solver needs to be able to undo and go back to the unmodified state from one particular state over and over to try pushes.

**Comment by tpict** [comment]
ah, if you have to use undos then it's fine

**Comment by Gantonator** [comment]
It isn't just used to find accessibleSpaces() I mean.  It's used to put the player in a position, push a box, then get a new savestate and then undo.

**Comment by Gantonator** [comment]
Cool.  Haha I will rewrite that comment anyway.

**Comment by tpict** [comment]
it's ok i've already done the docs for sokobanmap
